services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    expose:
      - 9000
    depends_on:
      - pgsql
    networks:
      - appnet
    entrypoint: [ "/bin/sh", "-c", "composer install && php-fpm" ]

  node:
    build:
      context: ./
      dockerfile: Dockerfile.node
    volumes:
      - ./:/root/app
    working_dir: /root/app
    ports:
      - 5173:5173
    networks:
      - appnet
    entrypoint: [ "/bin/sh", "-c", "npm install && npm run dev" ]

  pgsql:
    image: postgres:15.0-alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME:-hws}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
      - POSTGRES_DB=${DB_DATABASE:-laravel}
    ports:
      - 12345:5432
    networks:
      - appnet
    volumes:
      - pgsql-data:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    working_dir: /var/www/html
    ports:
      - 8000:443
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=443
    networks:
      - appnet
    depends_on:
      - app
      - node
      - pgsql

networks:
  appnet:
    driver: bridge

volumes:
  pgsql-data:
    driver: local
